name: 'Sync branched'
description: 'Creates and merges a PR to keep branches in sync'
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true
  FROM_BRANCH:
    description: "Branch from make pull-request from"
    required: true
  TO_BRANCH:
    description: "Branch to make the pull-request against"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
